### ISSUE TITLE
JSON Errors When Using .stats or .nhl

### ISSUE THREAD

**Issue by geeklex** [Ashiudo/stats.pl#1]
Current Environment is Ubuntu 16.04.3 LTS, perl version 5.22.1, libjason-perl 2.90-1.  After loading plugin in WeeChat 1.4 I get the following console output errors when running any ".stats" or ".nhl" commands. 

```
15:45:48 weechat perl | error: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of
                      | string)") at stats.pl line 2885.
15:45:48 weechat perl | error: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of
                      | string)") at stats.pl line 2184.
15:45:48 weechat perl | warning: Use of uninitialized value in numeric ge (>=) at stats.pl line 242.
```

**Comment by Ashiudo** [comment]
I think it's not grabbing any data, do you have links and curl installed? They are required to download some https sources.
\# sudo apt install links curl
Please let me know if it's something else I can help further!

**Comment by geeklex** [comment]
That was exactly it. Thank you for your help.

May I say that this is an excellent tool/program. Thank you for your hard work.

**Comment by Ashiudo** [comment]
No problem! Thank you for bringing that to my attention.
I've updated the readme so people will know what's required.
